=== ekapratamap/Q2A20171X/quizweb.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="banksoal">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="soal"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="soal">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="mk"/>
                <xs:element ref="dosen"/>
                <xs:element ref="tipe"/>
                <xs:element ref="kode"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="mk">
    	<xs:simpleType>
    		<xs:restriction base="xs:integer">



    			<xs:minInclusive value="1"></xs:minInclusive>
    		</xs:restriction>
    	</xs:simpleType>
    </xs:element>
    <xs:element name="dosen">
    	<xs:simpleType>
    		<xs:restriction base="xs:NCName">
    			<xs:minLength value="1"></xs:minLength>

    		</xs:restriction>
    	</xs:simpleType>
    </xs:element>
    <xs:element name="tipe">
    	<xs:simpleType>
    		<xs:restriction base="xs:NCName">
    			<xs:minLength value="1"></xs:minLength>
    			<xs:maxLength value="10"></xs:maxLength>
    			<xs:pattern value="ESSAY"></xs:pattern>
    			<xs:pattern value="PILGANDA"></xs:pattern>
    		</xs:restriction>
    	</xs:simpleType>
    </xs:element>
    <xs:element name="kode">
    	<xs:simpleType>
    		<xs:restriction base="xs:string">
    			<xs:minLength value="1"></xs:minLength>

    			<xs:pattern value=".+"></xs:pattern>
    			<xs:pattern value="PRAK/MK23/AA123"></xs:pattern>
    			<xs:pattern value="TEO/MK33/BB345"></xs:pattern>
    		</xs:restriction>
    	</xs:simpleType>
    </xs:element>
</xs:schema>

=== ekapratamap/Q2A20171X/quizweb.xml
<?xml version="1.0" encoding="UTF-8"?>
<banksoal xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="quizweb.xsd"> 
	<soal>
		<mk>123</mk>
		<dosen>Beri</dosen>
		<tipe>ESSAY</tipe>
		<kode>PRAK/MK23/BB345</kode>			
	</soal>
	<soal>
		<mk>122</mk>
		<dosen>Susi</dosen>
		<tipe>PILGANDA</tipe>	
		<kode>TEO/MK33/AA123</kode>			
	</soal>
	
</banksoal>
